version: 2.1

orbs:
  kube: circleci/kubernetes@0.10.0

jobs:
  test-deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - kube/install
      - run:
          name: Deploy to Kubernetes
          command: |
            kubectl apply -f k8s/deployment.yaml

workflows:
  version: 2
  test-deployment:
    jobs:
      - test-deploy