version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Plan a deploy
          command: |
            circleci run release plan k8s-main-app \
              --environment-name=development \
              --component-name=k8s-main-app-ui \
              --target-version=0.0.1 \
              --namespace=main-app
      - run:
          name: Update a deploy to SUCCESS
          command: circleci run release update k8s-main-app --status=SUCCESS
          when: on_success
      - run:
          name: Update planned deploy to FAILED
          command: circleci run release update k8s-main-app --status=FAILED
          when: on_fail

workflows:
  version: 2
  deploy-workflow:
    jobs:
      - deploy