version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Deploying
          command: |
            circleci run release update k8s-eastus --status=running
  cancel-deploy:
    docker:
      - image: cimg/go:stable
    steps:
      - run:
          name: Update planned release to CANCELED
          command: |
            circleci run release update --status=SUCCESS

workflows:
  version: 2
  deploy-workflow:
    jobs:
      - deploy
      - cancel-deploy